name: base_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^6.0.1
  flutter_launcher_icons: ^0.9.0
  wakelock: ^0.4.0
  collection: ^1.15.0

  # Firebase
  firebase_core: ^1.2.0
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.3
  firebase_messaging: ^10.0.0
  firebase_auth: ^3.1.1

  #app_review
  app_review: ^2.1.1+1

  #env
  flutter_dotenv: ^5.0.2

  # Logger
  simple_logger: ^1.8.0+1

  # LocalDatabase
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3

  # Riverpod
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.1+1
  freezed_annotation: ^0.14.1

  # ApiClient
  chopper: ^4.0.0-nullsafety.0

  # Dialog
  adaptive_dialog: ^0.10.0+5

  # Album and camera
  image_picker: ^0.7.3
  image_cropper: ^1.4.1

  # Calendar
  table_calendar: ^3.0.0-nullsafety.1

  # Onboarding
  introduction_screen: ^2.0.0

  # Sound
  flutter_sound: ^8.1.4

# multi select
  multi_select_flutter: ^4.0.0

  #Video_player
  video_player: ^2.1.0

  # Access local storage
  path_provider: ^2.0.1

  # Date
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1

  # Reactive
  rxdart: ^0.26.0

  # Cache image
  extended_image: ^4.0.0

  # Data share
  share: ^2.0.1

  # WebView
  webview_flutter: ^2.0.2

  # Launcher
  url_launcher: ^6.0.3
  map_launcher: ^2.0.0

  # QRcode
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0

  # Notification
  flutter_local_notifications: ^5.0.0+1
  flutter_native_timezone: ^1.0.10

  # Other
  uuid: ^3.0.3
  flutter_slidable: ^0.6.0-nullsafety.0
  package_info: ^2.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^2.0.0-nullsafety.1
  geocoding: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono: ^1.11.0+2

  # Serializer
  json_serializable: ^4.1.0

  # Code generator
  build_runner: ^1.12.2
  chopper_generator: ^4.0.0-nullsafety.0
  freezed: ^0.14.1+1
  flutter_gen_runner: ^3.0.2
  flutter_native_splash: ^1.1.7+1

flutter_gen:
  # https://github.com/FlutterGen/flutter_gen#configuration-file
  output: lib/gen/  # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/


flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo04-middle.png"
  fullscreen: true

flutter_icons:
  image_path_android: "assets/images/icon1024.png"
  image_path_ios: "assets/images/icon1024.png"
  android: true
  ios: true

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
