# 全てのユーザーが所属するコレクション
users: # collection
  documentId: userId = auth.uid
  userId: string
  email: string
  password: string
  name: string
  imageUrl: string
  birthday: string
  gender: string
  role: string
  job: string
  passionForService: string
  comment: string
  teamId: string
  executiveId: string
  inviteMember: bool
  checkNotification: bool
  transparency: bool
  createdAt: timestamp
  updatedAt: timestamp

# チームのコレクション
teams: # collection
  documentId: auto
  createdAt: timestamp
  updatedAt: timestamp
  users:
    documentId: auto
    userId: userId = auth.uid
  serviceShort: string
  imageId: string
  genreId: string
  serviceWorkId: string
  coWorkGoalIds: array(string)
  vision : string
  background: string


#target
targets:
  documentId: auto
  targetId: string
  name: string

#genres
genres:
  documentId: auto
  genreId: string
  name: string

#structures
structures:
  documentId: auto
  structureId: string
  name: string

#purposes
purposes:
  documentId: auto
  purposeId: string
  name: string

#finalGroups
finalGroups:
  documentId: auto
  finalGroupId: string
  name: string

# 第２リリースで追加する?
# readStatus, ContactFromOperation , ConversationGroup, CoworkOperation, Message,